# Generated by Django 4.2.30 on 2026-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('week', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=100)),
                ('units_sold', models.IntegerField(default=0)),
                ('gross_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_sales_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('markdown_percentage', models.DecimalField(db_column='markdown_percent', decimal_places=2, default=0.0, max_digits=5)),
                ('ending_stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_data',
            },
        ),
    ]
