# Generated by Django 4.2.30 on 2026-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_code', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('item_class', models.CharField(blank=True, max_length=255, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_qty', models.IntegerField(default=0)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ending_on_hand_qty', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dashboard_data',
                'indexes': [models.Index(fields=['store_code', 'item_code', 'date'], name='dashboard_d_store_c_4587e7_idx')],
            },
        ),
    ]
