# Generated by Django 4.2.30 on 2026-05-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_dashboarddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
