# Generated by Django 4.2.30 on 2026-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
